openapi: 3.0.1
info:
  title: Entra Secure Score API
  version: 1.0.0
  description: A very simple API to get the current Entra Secure Score.
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /security/secureScores:
    get:
      summary: Get Entra Secure Score
      operationId: getSecureScore
      description: Retrieves the secure score information for your tenant.
      security:
        - AADDelegatedAuth:
            - SecurityScore.Read.All
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                # The schema is a simple object with a depth of 1.
                type: object
                properties:
                  currentScore:
                    type: number
                    description: The tenant's current attained secure score.
                  maxScore:
                    type: number
                    description: The maximum possible score.
                  scoreInPercentage:
                    type: number
                    description: The score as a percentage.
                  lastUpdatedDateTime:
                    type: string
                    format: date-time
                    description: The time the score was last updated.
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
